require:
  - rubocop-rake

inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'

Bundler/DuplicatedGem:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Style/CaseEquality:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
