test:
  adapter: postgresql
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
